In [4]:
######################################################

import urllib.request  # 웹 url을 파이썬이 인식할 수 있게하는 패키지
from bs4 import BeautifulSoup  # html에서 검색 용이하게 하는 패키지
from selenium import webdriver  # 웹 애플리케이션의 테스트를 자동화하기 위한 프레임 워크 (손으로 클릭하듯이 작동)
from selenium.webdriver.common.keys import Keys
import time                     # 중간중간 sleep 을 걸어야 해서 time 모듈 import
import re

########################### url 받아오기 ###########################
# 웹브라우져로 크롬을 사용할거라서 크롬 드라이버를 다운받아 위의 위치에 둔다
# 팬텀 js로 하면 백그라운드로 실행할 수 있음!
binary = 'c:\\ddata\\chromedriver\\chromedriver.exe'

# 브라우져를 인스턴스화
browser = webdriver.Chrome(binary)

browser.get("https://flickr.com/")

# 구글의 이미지 검색에 해당하는 input 창의 id 가 '?' 임(검색창에 해당하는 html코드를 찾아서 elem 사용하도록 설정)
# input창의 id나 class 가져오기
#elem = browser.find_elements_by_class_name('gLFyf gsfi')
elem = browser.find_element_by_xpath("//*[@id='search-field']")

########################### 검색어 입력 ###########################
# elem 이 input 창과 연결되어 스스로 입력한 단어를 검색
elem.send_keys("camellia")

# 웹에서의 submit 은 엔터의 역할을 함
elem.submit()

########################### 반복할 횟수 ###########################
# 스크롤을 내리려면 브라우져 이미지 검색결과 부분(바디부분)에 마우스 클릭 한번 하고 키보드의 End키를 눌러야함
for i in range(1, 10):
    browser.find_element_by_xpath("//body").send_keys(Keys.END)
    try:
        browser.find_element_by_class_name("alt").click()
         #smb는 결과더보기. 그걸 클릭!
        #사진 뽑다보면
        time.sleep(5)
    except:
        time.sleep(10)                  # END 키 누르고 내려가는데 시간이 걸려서 sleep 해줌

# 네트워크 느릴까봐 안정성 위해 sleep 해줌 (웹에서 이미지 로드 시간동안 대기)
time.sleep(10)

html = browser.page_source         # 크롬브라우져에서 현재 불러온 소스 가져옴
soup = BeautifulSoup(html, "lxml")  # html 코드를 검색할 수 있도록 설정

########################### 그림파일 저장 ###########################

def fetch_list_url():
    params = []
    # 구글 이미지 url 이 있는 img 태그의 _img 클래스에 가서
    imgList = soup.find_all("div", class_="view photo-list-photo-view awake")
    for im in imgList:
        url = 'https:'+re.search(r'url\("(.+)"\)', im["style"]).group(1)
        params.append(url)                   # params 리스트에 image url 을 담음
    return params  # 이미지 상세 url

# 이미지의 상세 url 의 값이 있는 src 가 없을 경우
# data-src 로 가져오시오 ~

def fetch_detail_url():
    params = fetch_list_url()
    for idx, p in enumerate(params, 1):  # 이미지 명들을 index로 변경해서 저장

        # 다운받을 폴더경로 입력
        urllib.request.urlretrieve(p, "c:\\ddata\\im2\\ca" + str(idx) + ".jpg")

# enumerate 는 리스트의 모든 요소를 인덱스와 쌍으로 추출
# 하는 함수 . 숫자 1은 인덱스를 1부터 시작해라 ~

fetch_detail_url()

# 끝나면 브라우져 닫기
browser.quit()

In [1]:
#pip install opencv-python
import cv2 # 이미지를 숫자로 바꾸는 모듈
import os # os에서 파일 위치 차즌 모듈
import numpy as np

path = 'C:\\Users\\knit\\Downloads\\fire-detection-master\\Datasets 1-2\\nn'

file_list = os.listdir(path) # 파일명 가져오기

for k in file_list: # 파일명 리스트를 하나씩 가져온다.
#     try:
        img = cv2.imread(path + '\\' + k) # 사진을 숫자 행렬로 변환
        print(img)
        width, height = img.shape[:2] # 행렬 shape를 가져온다.
        resize_img = cv2.resize(img, (224 , 224), interpolation=cv2.INTER_CUBIC) 
        #32x32로 리사이즈
        cv2.imwrite('C:\\Users\\knit\\Downloads\\fire-detection-master\\Datasets 1-2\\nn2\\' + k, resize_img)
#         print(k)
#     except:
#         print(k)
#         pass



[[[ 32  50 109]
  [ 32  50 109]
  [ 32  50 109]
  ...
  [ 15  19  44]
  [  9  13  38]
  [  5   9  34]]

 [[ 36  54 113]
  [ 36  54 113]
  [ 36  54 113]
  ...
  [ 16  20  45]
  [ 10  14  39]
  [  6  10  35]]

 [[ 41  61 119]
  [ 41  61 119]
  [ 41  61 119]
  ...
  [ 17  22  47]
  [ 12  17  42]
  [  8  13  38]]

 ...

 [[ 74  91 158]
  [ 74  92 157]
  [ 74  91 158]
  ...
  [ 76  86 116]
  [ 76  86 116]
  [ 76  86 116]]

 [[ 74  92 157]
  [ 74  92 157]
  [ 74  92 157]
  ...
  [ 76  86 116]
  [ 76  86 116]
  [ 76  86 116]]

 [[ 74  92 157]
  [ 74  92 157]
  [ 74  92 157]
  ...
  [ 76  86 116]
  [ 76  86 116]
  [ 76  86 116]]]
[[[107  90  57]
  [105  88  55]
  [102  87  55]
  ...
  [ 20  13  20]
  [ 24  16  26]
  [ 22  14  24]]

 [[107  89  58]
  [104  89  57]
  [102  87  55]
  ...
  [ 21  14  21]
  [ 21  13  23]
  [ 18  10  20]]

 [[105  89  60]
  [104  88  59]
  [102  86  57]
  ...
  [ 25  19  24]
  [ 17  10  17]
  [ 24  17  24]]

 ...

 [[107  84  76]
  [105  84  76]
  [106  83  75]
  ..

[[[ 37  24  32]
  [ 38  25  33]
  [ 38  25  33]
  ...
  [109 147 135]
  [125 163 151]
  [129 169 157]]

 [[ 37  24  32]
  [ 38  25  33]
  [ 38  25  33]
  ...
  [118 158 146]
  [130 173 160]
  [136 179 166]]

 [[ 38  25  33]
  [ 38  25  33]
  [ 38  25  33]
  ...
  [126 170 157]
  [134 180 167]
  [137 186 172]]

 ...

 [[ 45  37  48]
  [ 45  37  48]
  [ 46  38  49]
  ...
  [ 50  40  52]
  [ 50  40  52]
  [ 50  40  52]]

 [[ 46  38  49]
  [ 46  38  49]
  [ 47  39  50]
  ...
  [ 52  42  54]
  [ 52  42  54]
  [ 51  41  53]]

 [[ 46  38  49]
  [ 47  39  50]
  [ 47  39  50]
  ...
  [ 53  43  55]
  [ 53  43  55]
  [ 53  43  55]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

  [236 226 255]]]
[[[ 5 20 36]
  [ 5 20 36]
  [ 5 20 36]
  ...
  [ 4  6  7]
  [ 4  6  7]
  [ 4  6  7]]

 [[ 5 20 36]
  [ 5 20 36]
  [ 5 20 36]
  ...
  [ 4  6  7]
  [ 4  6  7]
  [ 4  6  7]]

 [[ 6 20 38]
  [ 6 20 38]
  [ 6 20 38]
  ...
  [ 4  6  7]
  [ 4  6  7]
  [ 4  6  7]]

 ...

 [[94 92 92]
  [94 92 92]
  [95 93 93]
  ...
  [16 25 39]
  [16 25 39]
  [15 24 38]]

 [[94 92 92]
  [94 92 92]
  [95 93 93]
  ...
  [16 25 39]
  [15 24 38]
  [15 24 38]]

 [[94 92 92]
  [94 92 92]
  [95 93 93]
  ...
  [15 24 38]
  [15 24 38]
  [15 24 38]]]
[[[ 1  2 12]
  [ 1  2 12]
  [ 1  2 12]
  ...
  [ 0  0 10]
  [ 0  0 10]
  [ 0  0 11]]

 [[ 1  2 12]
  [ 1  2 12]
  [ 1  2 12]
  ...
  [ 0  0 10]
  [ 0  0 10]
  [ 0  0 10]]

 [[ 1  2 12]
  [ 1  2 12]
  [ 1  2 12]
  ...
  [ 1  3 11]
  [ 1  4  9]
  [ 1  3 11]]

 ...

 [[ 0  1  9]
  [ 0  1  9]
  [ 0  1  9]
  ...
  [ 1  2 12]
  [ 2  3 13]
  [ 2  3 13]]

 [[ 0  1  9]
  [ 0  1  9]
  [ 0  1  9]
  ...
  [ 1  2 12]
  [ 2  3 13]
  [ 2  3 13]]

 [[ 0  1  9]
  [ 0  1  9

[[[129 114 141]
  [130 115 142]
  [130 115 143]
  ...
  [ 69  73  78]
  [ 66  72  77]
  [ 66  72  77]]

 [[128 113 140]
  [130 115 142]
  [131 116 144]
  ...
  [ 68  72  77]
  [ 65  71  76]
  [ 65  71  76]]

 [[126 111 138]
  [129 114 141]
  [131 116 144]
  ...
  [ 67  71  76]
  [ 64  70  75]
  [ 64  70  75]]

 ...

 [[ 80 106 153]
  [ 92 118 165]
  [ 87 112 162]
  ...
  [119 123 164]
  [120 124 165]
  [121 125 166]]

 [[ 76 103 153]
  [ 84 111 161]
  [ 87 114 164]
  ...
  [121 124 168]
  [121 124 168]
  [122 125 169]]

 [[ 84 111 161]
  [ 87 114 164]
  [ 92 119 170]
  ...
  [121 127 170]
  [121 127 170]
  [122 128 171]]]
[[[191 203 251]
  [191 203 251]
  [191 203 251]
  ...
  [101  92 135]
  [100  91 134]
  [100  91 134]]

 [[191 203 251]
  [191 203 251]
  [191 203 251]
  ...
  [101  92 135]
  [100  91 134]
  [100  91 134]]

 [[191 203 251]
  [191 203 251]
  [191 203 251]
  ...
  [101  92 135]
  [100  91 134]
  [100  91 134]]

 ...

 [[ 18  10  33]
  [ 19  11  34]
  [ 20  12  35]
  ..

  [ 1  1  1]]]
[[[24 22 28]
  [25 23 29]
  [26 24 30]
  ...
  [17 17 33]
  [16 16 34]
  [15 15 33]]

 [[24 22 28]
  [25 23 29]
  [26 24 30]
  ...
  [18 18 34]
  [16 16 34]
  [15 15 33]]

 [[25 23 29]
  [25 23 29]
  [27 25 31]
  ...
  [18 18 34]
  [17 17 35]
  [15 15 33]]

 ...

 [[26 33 50]
  [30 38 55]
  [31 38 57]
  ...
  [12 32 49]
  [13 36 52]
  [16 39 55]]

 [[31 38 55]
  [34 42 59]
  [35 42 61]
  ...
  [11 31 48]
  [12 35 51]
  [15 38 54]]

 [[36 43 60]
  [38 46 63]
  [39 46 65]
  ...
  [ 9 29 46]
  [10 33 49]
  [13 36 52]]]
[[[16 16 16]
  [13 13 13]
  [10 10 10]
  ...
  [11 15 20]
  [11 15 20]
  [11 15 20]]

 [[15 15 15]
  [12 12 12]
  [10 10 10]
  ...
  [11 15 20]
  [11 15 20]
  [11 15 20]]

 [[12 12 12]
  [11 11 11]
  [ 9  9  9]
  ...
  [11 15 20]
  [11 15 20]
  [11 15 20]]

 ...

 [[ 7  9 10]
  [ 7  9 10]
  [ 7  9 10]
  ...
  [10 11 15]
  [11 12 16]
  [11 12 16]]

 [[ 7  9 10]
  [ 7  9 10]
  [ 7  9 10]
  ...
  [ 9 10 14]
  [10 11 15]
  [11 12 16]]

 [[ 7  9 10]
  [ 7  9 10]
 

  [146 166 177]]]
[[[101 172 137]
  [ 86 159 123]
  [ 68 145 115]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[106 178 144]
  [ 92 165 131]
  [ 77 153 125]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 92 164 134]
  [ 92 160 131]
  [ 84 154 128]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[  0  10   3]
  [ 10  16  11]
  [ 11  18  15]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0  11   4]
  [  5  13   5]
  [  3  12   6]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  4  20  12]
  [ 12  21  13]
  [ 11  20  12]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[ 11   9  68]
  [ 10  11  67]
  [ 11  12  70]
  ...
  [ 14  10  45]
  [ 14  10  46]
  [ 12  10  39]]

 [[ 10  11  69]
  [ 11  12  70]
  [ 13  13  73]
  ...
  [ 12  11  43]
  [ 10   8  38]
  [ 15  10  41]]

 [[  9  10  68]
  [ 12  13  71]
  [ 11  12  70]
  ...
  [  9  10  44]
  [ 11  11  41]
  [ 14  10  45]]

 ...

 [[205 189 160]
  [205 188 161]
  

[[[162 154 147]
  [192 184 177]
  [229 221 214]
  ...
  [219 199 182]
  [219 199 182]
  [224 204 187]]

 [[250 241 237]
  [240 231 227]
  [220 211 207]
  ...
  [218 198 181]
  [218 198 181]
  [223 203 186]]

 [[215 206 203]
  [206 197 194]
  [191 182 179]
  ...
  [216 196 179]
  [216 196 179]
  [220 200 183]]

 ...

 [[ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]
  ...
  [ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]]

 [[ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]
  ...
  [ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]]

 [[ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]
  ...
  [ 54  12 167]
  [ 54  12 167]
  [ 54  12 167]]]
[[[178 172 173]
  [177 171 172]
  [175 169 170]
  ...
  [ 56  83  73]
  [ 53  80  70]
  [ 61  88  78]]

 [[172 166 167]
  [171 165 166]
  [170 164 165]
  ...
  [ 50  75  65]
  [ 39  64  54]
  [ 53  78  68]]

 [[163 157 158]
  [163 157 158]
  [163 157 158]
  ...
  [ 39  63  53]
  [ 43  67  57]
  [ 73  97  87]]

 ...

 [[ 38  44  43]
  [ 38  44  43]
  [ 38  44  43]
  ..

[[[ 53 130 102]
  [ 47 129 100]
  [ 39 131 102]
  ...
  [ 14  10  15]
  [ 16  12  17]
  [ 20  16  21]]

 [[ 43 120  92]
  [ 40 124  95]
  [ 39 131 102]
  ...
  [ 15  14  16]
  [ 14  13  15]
  [ 17  16  18]]

 [[ 40 120  91]
  [ 42 126  97]
  [ 43 135 106]
  ...
  [ 13  18  17]
  [ 13  15  15]
  [ 12  14  14]]

 ...

 [[ 69 106 110]
  [ 36  73  77]
  [  6  44  48]
  ...
  [ 43 148 103]
  [ 40 148 102]
  [ 36 146  98]]

 [[ 55  85  90]
  [ 39  71  76]
  [ 38  73  77]
  ...
  [ 20 125  80]
  [  8 118  70]
  [  2 115  65]]

 [[ 71 100 105]
  [ 74 104 109]
  [ 90 120 125]
  ...
  [  2 111  63]
  [  0 100  52]
  [  0 101  51]]]
[[[247 245 205]
  [251 248 210]
  [255 252 217]
  ...
  [145 150 105]
  [140 145 100]
  [135 140  95]]

 [[249 246 208]
  [254 251 213]
  [255 255 222]
  ...
  [140 145 100]
  [135 140  95]
  [131 136  91]]

 [[251 245 210]
  [255 252 217]
  [255 255 227]
  ...
  [142 146 104]
  [138 142 100]
  [135 139  97]]

 ...

 [[  0  17  12]
  [ 27  86  82]
  [ 29  79  77]
  ..

  [ 0  2  2]]]
[[[ 71  88  55]
  [ 55  72  39]
  [ 50  66  35]
  ...
  [ 99 133  49]
  [ 88 120  31]
  [ 85 118  27]]

 [[ 68  84  53]
  [ 64  80  49]
  [ 60  76  45]
  ...
  [ 92 125  44]
  [ 61  94   9]
  [ 52  84   0]]

 [[ 51  66  38]
  [ 59  74  46]
  [ 61  76  48]
  ...
  [ 68 100  23]
  [ 63  95  14]
  [ 83 116  32]]

 ...

 [[ 26  30  24]
  [ 35  39  33]
  [ 36  40  34]
  ...
  [ 73 112  67]
  [ 52  93  48]
  [ 26  67  22]]

 [[ 25  29  23]
  [ 34  38  32]
  [ 36  40  34]
  ...
  [ 64 106  58]
  [ 74 116  68]
  [ 84 126  78]]

 [[ 26  30  24]
  [ 30  34  28]
  [ 33  37  31]
  ...
  [ 67 110  59]
  [ 47  90  39]
  [ 44  87  36]]]
[[[ 4  6 17]
  [ 4  6 17]
  [ 4  6 17]
  ...
  [ 1  0  2]
  [ 3  5  6]
  [ 6 10 11]]

 [[ 4  6 17]
  [ 4  6 17]
  [ 4  6 17]
  ...
  [ 1  0  2]
  [ 3  5  6]
  [ 6 10 11]]

 [[ 4  6 17]
  [ 4  6 17]
  [ 4  6 17]
  ...
  [ 1  0  2]
  [ 3  5  6]
  [ 6 10 11]]

 ...

 [[ 1  4  8]
  [ 1  4  8]
  [ 1  4  8]
  ...
  [ 0  2  3]
  [ 0  2  3]
  [ 0  2  3]]

 [[ 1

[[[  3   0  26]
  [  3   0  26]
  [  3   0  26]
  ...
  [  0   1  39]
  [  0   1  39]
  [  0   1  39]]

 [[  3   0  26]
  [  3   0  26]
  [  3   0  26]
  ...
  [  0   1  39]
  [  0   1  39]
  [  0   1  39]]

 [[  3   0  26]
  [  3   0  26]
  [  3   0  26]
  ...
  [  0   1  39]
  [  0   1  39]
  [  0   1  39]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 90  91 135]
  [ 87  88 132]
  [ 80  85 130]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 89  90 134]
  [ 86  87 131]
  [ 79  84 129]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 89  90 134]
  [ 86  87 131]
  [ 79  84 129]]]
[[[202 198 193]
  [202 198 193]
  [202 198 193]
  ...
  [190 187 182]
  [189 186 181]
  [189 186 181]]

 [[202 198 193]
  [202 198 193]
  [202 198 193]
  ...
  [190 187 182]
  [189 186 181]
  [189 186 181]]

 [[202 198 193]
  [202 198 193]
  [202 198 193]
  ...
  [190 187 182]
  [189 186 181]
  [189 186 181]]

 ...

 [[110 123 121]
  [ 47  61  59]
  [ 56  69  67]
  ..

  [  9  11  11]]]
[[[24 35 55]
  [26 37 57]
  [27 38 58]
  ...
  [14 13 17]
  [14 13 17]
  [14 13 17]]

 [[26 37 57]
  [26 37 57]
  [27 38 58]
  ...
  [14 13 17]
  [14 13 17]
  [14 13 17]]

 [[28 39 59]
  [27 38 58]
  [26 37 57]
  ...
  [14 13 17]
  [14 13 17]
  [14 13 17]]

 ...

 [[ 2  1  3]
  [ 2  1  3]
  [ 2  1  3]
  ...
  [16 19 17]
  [18 21 19]
  [23 26 24]]

 [[ 2  1  3]
  [ 2  1  3]
  [ 2  1  3]
  ...
  [17 20 18]
  [18 21 19]
  [20 23 21]]

 [[ 2  1  3]
  [ 2  1  3]
  [ 2  1  3]
  ...
  [21 24 22]
  [21 24 22]
  [20 23 21]]]
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 4  1 40]
  [ 4  1 40]
  [ 4  1 40]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 4  1 40]
  [ 4  1 40]
  [ 4  1 40]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 4  1 40]
  [ 4  1 40]
  [ 4  1 40]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0

  [187 173 154]]]
[[[106  96  89]
  [102  96  83]
  [ 98  96  86]
  ...
  [ 97  90  97]
  [104  99 100]
  [107 104 106]]

 [[101  94  85]
  [102  94  81]
  [102  96  85]
  ...
  [ 95  88  95]
  [110 102 112]
  [112 105 118]]

 [[100  91  82]
  [104  94  87]
  [ 98  88  81]
  ...
  [101  94 101]
  [115 107 114]
  [102  92 109]]

 ...

 [[ 74  61  59]
  [ 67  48  40]
  [ 46  27  12]
  ...
  [ 92 105  81]
  [ 99  98  72]
  [ 84  63  66]]

 [[ 66  52  46]
  [ 66  48  41]
  [ 39  28   6]
  ...
  [102 106  95]
  [106 104  93]
  [ 95  64  73]]

 [[ 66  50  38]
  [ 54  37  28]
  [ 35  19   6]
  ...
  [128 137 124]
  [128 131 116]
  [132  99  90]]]
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  

[[[  1  12  62]
  [  1  12  62]
  [  3  14  64]
  ...
  [  4  66 214]
  [  4  66 214]
  [  4  66 214]]

 [[  1  12  62]
  [  1  12  62]
  [  3  14  64]
  ...
  [  4  66 214]
  [  4  66 214]
  [  4  66 214]]

 [[  1  12  62]
  [  1  12  62]
  [  3  14  64]
  ...
  [  4  66 214]
  [  4  66 214]
  [  4  66 214]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
[[[ 6  2  7]
  [ 6  4 10]
  [ 5  7 15]
  ...
  [42 36 53]
  [42 36 53]
  [42 36 53]]

 [[ 4  3  7]
  [ 2  2  8]
  [ 4  6 14]
  ...
  [42 36 53]
  [42 36 53]
  [42 36 53]]

 [[ 3  3  9]
  [ 2  5 10]
  [ 9 12 17]
  ...
  [42 36 53]
  [42 36 53]
  [42 36 53]]

 ...

 [[ 1  0  9]
  [ 1  0  9]
  [ 1  0  9]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  0  9]
  [ 1  